head:
  - testing:
    - testing
  - enhancement:
    - testing
    - refactor/**/*
  - glob:
    - features/**/*

base:
  - master:
    - master

files:
  - gitstar:
    - .git*
  - dot-github:
    - .github/**/*

