name: 'Pull Request Labeller'
description: 'Automatically label a pull request based on base and head branches'
author: 'Jack Ellis'
inputs:
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/pr-labeler.yml'
    required: true
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node12'
  main: 'dist/main.js'